# Generated by Django 5.0 on 2023-12-26 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linha1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('layer', models.CharField(verbose_name=255)),
                ('valores', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
